//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align.
        /// </summary>
        public static string Align {
            get {
                return ResourceManager.GetString("Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Bottom.
        /// </summary>
        public static string AlignBottom {
            get {
                return ResourceManager.GetString("AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Center.
        /// </summary>
        public static string AlignCenter {
            get {
                return ResourceManager.GetString("AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Center (Horizontal).
        /// </summary>
        public static string AlignCenterHorizontal {
            get {
                return ResourceManager.GetString("AlignCenterHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Center (Vertical).
        /// </summary>
        public static string AlignCenterVertical {
            get {
                return ResourceManager.GetString("AlignCenterVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Left.
        /// </summary>
        public static string AlignLeft {
            get {
                return ResourceManager.GetString("AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Right.
        /// </summary>
        public static string AlignRight {
            get {
                return ResourceManager.GetString("AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Top.
        /// </summary>
        public static string AlignTop {
            get {
                return ResourceManager.GetString("AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulleted.
        /// </summary>
        public static string Bulleted {
            get {
                return ResourceManager.GetString("Bulleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Format.
        /// </summary>
        public static string ClearFormat {
            get {
                return ResourceManager.GetString("ClearFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Text Formatting.
        /// </summary>
        public static string ClearTextFormatting {
            get {
                return ResourceManager.GetString("ClearTextFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows how to apply a custom style to the C1Menu control..
        /// </summary>
        public static string CustomMenuAppearanceDesc {
            get {
                return ResourceManager.GetString("CustomMenuAppearanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Appearance.
        /// </summary>
        public static string CustomMenuAppearanceTitle {
            get {
                return ResourceManager.GetString("CustomMenuAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use C1RadialMenu with C1RichTextBox.
        /// </summary>
        public static string CustomRadialContextMenuDesc {
            get {
                return ResourceManager.GetString("CustomRadialContextMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Context Menu.
        /// </summary>
        public static string CustomRadialContextMenuTitle {
            get {
                return ResourceManager.GetString("CustomRadialContextMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep1.
        /// </summary>
        public static string Deep1 {
            get {
                return ResourceManager.GetString("Deep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep2.
        /// </summary>
        public static string Deep2 {
            get {
                return ResourceManager.GetString("Deep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep3.
        /// </summary>
        public static string Deep3 {
            get {
                return ResourceManager.GetString("Deep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep4.
        /// </summary>
        public static string Deep4 {
            get {
                return ResourceManager.GetString("Deep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep5.
        /// </summary>
        public static string Deep5 {
            get {
                return ResourceManager.GetString("Deep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Table.
        /// </summary>
        public static string Delete_Table {
            get {
                return ResourceManager.GetString("Delete Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Cells.
        /// </summary>
        public static string DeleteCells {
            get {
                return ResourceManager.GetString("DeleteCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Columns.
        /// </summary>
        public static string DeleteColumns {
            get {
                return ResourceManager.GetString("DeleteColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Rows.
        /// </summary>
        public static string DeleteRows {
            get {
                return ResourceManager.GetString("DeleteRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the C1Menu control to create menu and C1ContextMenu control to attach pop-up menu to your interface. Nest menus to any depth, use an icon for each menu item along with the menu label, and even make menu items checkable..
        /// </summary>
        public static string DemoMenuDesc {
            get {
                return ResourceManager.GetString("DemoMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo C1Menu.
        /// </summary>
        public static string DemoMenuTitle {
            get {
                return ResourceManager.GetString("DemoMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use C1RadialMenu.
        /// </summary>
        public static string DemoRadialMenuDesc {
            get {
                return ResourceManager.GetString("DemoRadialMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo C1RadialMenu.
        /// </summary>
        public static string DemoRadialMenuTitle {
            get {
                return ResourceManager.GetString("DemoRadialMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document 1.
        /// </summary>
        public static string Document1 {
            get {
                return ResourceManager.GetString("Document1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document 2.
        /// </summary>
        public static string Document2 {
            get {
                return ResourceManager.GetString("Document2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document 3.
        /// </summary>
        public static string Document3 {
            get {
                return ResourceManager.GetString("Document3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document 4.
        /// </summary>
        public static string Document4 {
            get {
                return ResourceManager.GetString("Document4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create custom drop-downs using C1Menu. This demo shows how to create a dropdown menu using C1Menu inside a C1DropDownButton control..
        /// </summary>
        public static string DropDownMenuDesc {
            get {
                return ResourceManager.GetString("DropDownMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Down Menu.
        /// </summary>
        public static string DropDownMenuTitle {
            get {
                return ResourceManager.GetString("DropDownMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude From Project.
        /// </summary>
        public static string ExcludeFromProject {
            get {
                return ResourceManager.GetString("ExcludeFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive 1.
        /// </summary>
        public static string Exclusive1 {
            get {
                return ResourceManager.GetString("Exclusive1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive 2.
        /// </summary>
        public static string Exclusive2 {
            get {
                return ResourceManager.GetString("Exclusive2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive 3.
        /// </summary>
        public static string Exclusive3 {
            get {
                return ResourceManager.GetString("Exclusive3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing.
        /// </summary>
        public static string Existing {
            get {
                return ResourceManager.GetString("Existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Item.
        /// </summary>
        public static string ExistingItem {
            get {
                return ResourceManager.GetString("ExistingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        public static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Painter.
        /// </summary>
        public static string FormatPainter {
            get {
                return ResourceManager.GetString("FormatPainter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Above.
        /// </summary>
        public static string InsertAbove {
            get {
                return ResourceManager.GetString("InsertAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Below.
        /// </summary>
        public static string InsertBelow {
            get {
                return ResourceManager.GetString("InsertBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Left.
        /// </summary>
        public static string InsertLeft {
            get {
                return ResourceManager.GetString("InsertLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Object.
        /// </summary>
        public static string InsertObject {
            get {
                return ResourceManager.GetString("InsertObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Right.
        /// </summary>
        public static string InsertRight {
            get {
                return ResourceManager.GetString("InsertRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table.
        /// </summary>
        public static string InsertTable {
            get {
                return ResourceManager.GetString("InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        public static string Justify {
            get {
                return ResourceManager.GetString("Justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MenuItem_Close {
            get {
                return ResourceManager.GetString("MenuItem_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep.
        /// </summary>
        public static string MenuItem_Deep {
            get {
                return ResourceManager.GetString("MenuItem_Deep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuItem_Edit {
            get {
                return ResourceManager.GetString("MenuItem_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItem_Exit {
            get {
                return ResourceManager.GetString("MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MenuItem_Open {
            get {
                return ResourceManager.GetString("MenuItem_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Setup.
        /// </summary>
        public static string MenuItem_PageSetup {
            get {
                return ResourceManager.GetString("MenuItem_PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string MenuItem_Print {
            get {
                return ResourceManager.GetString("MenuItem_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string MenuItem_Redo {
            get {
                return ResourceManager.GetString("MenuItem_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuItem_Save {
            get {
                return ResourceManager.GetString("MenuItem_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string MenuItem_SaveAll {
            get {
                return ResourceManager.GetString("MenuItem_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string MenuItem_Undo {
            get {
                return ResourceManager.GetString("MenuItem_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string MenuItem_Window {
            get {
                return ResourceManager.GetString("MenuItem_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Cells.
        /// </summary>
        public static string MergeCells {
            get {
                return ResourceManager.GetString("MergeCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbered.
        /// </summary>
        public static string Numbered {
            get {
                return ResourceManager.GetString("Numbered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string RadialMenu_Redo {
            get {
                return ResourceManager.GetString("RadialMenu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string RadialMenu_Table {
            get {
                return ResourceManager.GetString("RadialMenu_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string RadialMenu_Undo {
            get {
                return ResourceManager.GetString("RadialMenu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _UndoRedo.
        /// </summary>
        public static string RadialMenu_UndoRedo {
            get {
                return ResourceManager.GetString("RadialMenu_UndoRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strike.
        /// </summary>
        public static string Strike {
            get {
                return ResourceManager.GetString("Strike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Solution.
        /// </summary>
        public static string SubMenuItem_CloseSolution {
            get {
                return ResourceManager.GetString("SubMenuItem_CloseSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string SubMenuItem_Copy {
            get {
                return ResourceManager.GetString("SubMenuItem_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string SubMenuItem_Cut {
            get {
                return ResourceManager.GetString("SubMenuItem_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SubMenuItem_Delete {
            get {
                return ResourceManager.GetString("SubMenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File....
        /// </summary>
        public static string SubMenuItem_File {
            get {
                return ResourceManager.GetString("SubMenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string SubMenuItem_New {
            get {
                return ResourceManager.GetString("SubMenuItem_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string SubMenuItem_Paste {
            get {
                return ResourceManager.GetString("SubMenuItem_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project....
        /// </summary>
        public static string SubMenuItem_Project {
            get {
                return ResourceManager.GetString("SubMenuItem_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Project....
        /// </summary>
        public static string SubMenuItem_TeamProject {
            get {
                return ResourceManager.GetString("SubMenuItem_TeamProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site....
        /// </summary>
        public static string SubMenuItem_WebSite {
            get {
                return ResourceManager.GetString("SubMenuItem_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        public static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        public static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Highlight Color.
        /// </summary>
        public static string TextHighlightColor {
            get {
                return ResourceManager.GetString("TextHighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        ///   Looks up a localized string similar to Shows how to display group labels between menu-items.
        /// </summary>
        public static string GroupingDesc {
            get {
                return ResourceManager.GetString("GroupingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string GroupingTitle {
            get {
                return ResourceManager.GetString("GroupingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show how to display a menu item whose header is a tile list view.
        /// </summary>
        public static string TilesDesc {
            get {
                return ResourceManager.GetString("TilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TileView Menu Item.
        /// </summary>
        public static string TilesTitle {
            get {
                return ResourceManager.GetString("TilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuExplorer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo/Redo.
        /// </summary>
        public static string UndoRedo {
            get {
                return ResourceManager.GetString("UndoRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmerge Cells.
        /// </summary>
        public static string UnmergeCells {
            get {
                return ResourceManager.GetString("UnmergeCells", resourceCulture);
            }
        }
    }
}
