<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Financial</AssemblyName>
    <RootNamespace>Financial</RootNamespace>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DefineConstants>TRACE;DEBUG;WPF</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineConstants>TRACE;WPF</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\data.zip" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="C1.Xaml.WPF">
      <Version>4.6.20261.19</Version>
    </PackageReference>
    <PackageReference Include="C1.Xaml.WPF.FlexGrid">
      <Version>4.6.20261.19</Version>
    </PackageReference>
    <PackageReference Include="C1.Zip" Version="10.0.20261.*" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\search.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include=".sa3licx" />
  </ItemGroup>
</Project>