//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThemeExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Code.
        /// </summary>
        public static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Code Type Description:.
        /// </summary>
        public static string BarCodeDescription {
            get {
                return ResourceManager.GetString("BarCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Barcode Image.
        /// </summary>
        public static string BarcodeImage {
            get {
                return ResourceManager.GetString("BarcodeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Barcode Type:.
        /// </summary>
        public static string BarcodeType {
            get {
                return ResourceManager.GetString("BarcodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1Window.
        /// </summary>
        public static string C1Window {
            get {
                return ResourceManager.GetString("C1Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is text in C1Window.
        /// </summary>
        public static string C1WindowText {
            get {
                return ResourceManager.GetString("C1WindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox.
        /// </summary>
        public static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Me!.
        /// </summary>
        public static string CheckMe {
            get {
                return ResourceManager.GetString("CheckMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click me!.
        /// </summary>
        public static string Clickme {
            get {
                return ResourceManager.GetString("Clickme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common WPF Controls.
        /// </summary>
        public static string CommonWPFControls {
            get {
                return ResourceManager.GetString("CommonWPFControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Filter.
        /// </summary>
        public static string DataFilter {
            get {
                return ResourceManager.GetString("DataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Management.
        /// </summary>
        public static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Pager.
        /// </summary>
        public static string DataPager {
            get {
                return ResourceManager.GetString("DataPager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Visualization.
        /// </summary>
        public static string DataVisualization {
            get {
                return ResourceManager.GetString("DataVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Button.
        /// </summary>
        public static string DefaultButton {
            get {
                return ResourceManager.GetString("DefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Grouping.
        /// </summary>
        public static string EnableGrouping {
            get {
                return ResourceManager.GetString("EnableGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expander.
        /// </summary>
        public static string Expander {
            get {
                return ResourceManager.GetString("Expander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Expander content.
        /// </summary>
        public static string Expander_content {
            get {
                return ResourceManager.GetString("Expander_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Editor.
        /// </summary>
        public static string FilterEditor {
            get {
                return ResourceManager.GetString("FilterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexChart.
        /// </summary>
        public static string FlexChart {
            get {
                return ResourceManager.GetString("FlexChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexGrid.
        /// </summary>
        public static string FlexGrid {
            get {
                return ResourceManager.GetString("FlexGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexPie.
        /// </summary>
        public static string FlexPie {
            get {
                return ResourceManager.GetString("FlexPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexPivot.
        /// </summary>
        public static string FlexPivot {
            get {
                return ResourceManager.GetString("FlexPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow me!.
        /// </summary>
        public static string Followme {
            get {
                return ResourceManager.GetString("Followme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauge.
        /// </summary>
        public static string Gauge {
            get {
                return ResourceManager.GetString("Gauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Box.
        /// </summary>
        public static string GroupBox {
            get {
                return ResourceManager.GetString("GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the GroupBox content.
        /// </summary>
        public static string GroupBox_content {
            get {
                return ResourceManager.GetString("GroupBox_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &amp; Editing.
        /// </summary>
        public static string InputEditing {
            get {
                return ResourceManager.GetString("InputEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number.
        /// </summary>
        public static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView.
        /// </summary>
        public static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation &amp; Layout.
        /// </summary>
        public static string NavigationLayout {
            get {
                return ResourceManager.GetString("NavigationLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        public static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type something.
        /// </summary>
        public static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadioButton.
        /// </summary>
        public static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly TextBoxBase.
        /// </summary>
        public static string Readonly {
            get {
                return ResourceManager.GetString("Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly TextBox.
        /// </summary>
        public static string Readonly_TextBox {
            get {
                return ResourceManager.GetString("Readonly_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting &amp; Documents.
        /// </summary>
        public static string ReportingDocuments {
            get {
                return ResourceManager.GetString("ReportingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows And Columns.
        /// </summary>
        public static string RowsAndColumns {
            get {
                return ResourceManager.GetString("RowsAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RulesManager.
        /// </summary>
        public static string RulesManager {
            get {
                return ResourceManager.GetString("RulesManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler View:.
        /// </summary>
        public static string SchedulerView {
            get {
                return ResourceManager.GetString("SchedulerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling.
        /// </summary>
        public static string Scheduling {
            get {
                return ResourceManager.GetString("Scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show week tabs.
        /// </summary>
        public static string Showweektabs {
            get {
                return ResourceManager.GetString("Showweektabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparkline.
        /// </summary>
        public static string Sparkline {
            get {
                return ResourceManager.GetString("Sparkline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio WPF Edition includes professional themes which expand your style possibilities..
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox: .
        /// </summary>
        public static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme: .
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Explorer.
        /// </summary>
        public static string ThemeExplorer {
            get {
                return ResourceManager.GetString("ThemeExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Explorer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle button.
        /// </summary>
        public static string Togglebutton {
            get {
                return ResourceManager.GetString("Togglebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle me!.
        /// </summary>
        public static string Toggleme {
            get {
                return ResourceManager.GetString("Toggleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string ViewType_Day {
            get {
                return ResourceManager.GetString("ViewType_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string ViewType_Month {
            get {
                return ResourceManager.GetString("ViewType_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeLine.
        /// </summary>
        public static string ViewType_TimeLine {
            get {
                return ResourceManager.GetString("ViewType_TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string ViewType_Week {
            get {
                return ResourceManager.GetString("ViewType_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkingWeek.
        /// </summary>
        public static string ViewType_WorkingWeek {
            get {
                return ResourceManager.GetString("ViewType_WorkingWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
