<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>SalesAnalysis.Data</AssemblyName>
    <RootNamespace>SalesAnalysis.Data</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseIISExpress>false</UseIISExpress>
    <DevelopmentServerPort>50297</DevelopmentServerPort>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.2.9" />
    <PackageReference Include="Microsoft.Data.Services.Client" Version="5.8.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.EnterpriseServices" />
    <Reference Include="System.Web.ApplicationServices" />
    <Reference Include="System.Web.DynamicData" />
    <Reference Include="System.Web.Entity" />
    <Reference Include="System.Web.Mobile" />
    <Reference Include="System.Web.Services" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="App_Data\NORTHWND.MDF" />
    <Content Include="NorthWindDataService.svc" />
    <Content Include="Scripts\**" />
  </ItemGroup>

  <ItemGroup>
    <EntityDeploy Include="NorthWindModel.edmx">
      <Generator>EntityModelCodeGenerator</Generator>
      <LastGenOutput>NorthWindModel.Designer.cs</LastGenOutput>
    </EntityDeploy>
  </ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include=".sa3licx" />
	</ItemGroup>
</Project>
