<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>FlexChart101</RootNamespace>
    <AssemblyName>FlexChart101</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\SamplesCodes.zip" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="C1.Xaml.WPF">
      <Version>4.6.20261.8</Version>
    </PackageReference>
    <PackageReference Include="C1.Xaml.WPF.DX">
      <Version>4.6.20261.8</Version>
    </PackageReference>
    <PackageReference Include="C1.Xaml.WPF.FlexChart">
      <Version>4.6.20261.8</Version>
    </PackageReference>
    <PackageReference Include="C1.Xaml.WPF.RichTextBox">
      <Version>4.6.20261.8</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="C1.Zip" Version="10.0.20261.*" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include=".sa3licx" />
  </ItemGroup>
</Project>