//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InputExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddItems.
        /// </summary>
        public static string AddItemsEvent {
            get {
                return ResourceManager.GetString("AddItemsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tag.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTag.
        /// </summary>
        public static string AddTagButton {
            get {
                return ResourceManager.GetString("AddTagButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Text.
        /// </summary>
        public static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be someone at least {1} years of age.
        /// </summary>
        public static string AgeRequirement {
            get {
                return ResourceManager.GetString("AgeRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not work more than 8 hours.
        /// </summary>
        public static string CanNotWorkMoreThan {
            get {
                return ResourceManager.GetString("CanNotWorkMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters are not allowed..
        /// </summary>
        public static string CharactersNotAllowed {
            get {
                return ResourceManager.GetString("CharactersNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use C1CheckList.
        /// </summary>
        public static string CheckListDes {
            get {
                return ResourceManager.GetString("CheckListDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckList.
        /// </summary>
        public static string CheckListTitle {
            get {
                return ResourceManager.GetString("CheckListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Tag.
        /// </summary>
        public static string EnterTag {
            get {
                return ResourceManager.GetString("EnterTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string EventsTabHeader {
            get {
                return ResourceManager.GetString("EventsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1Expander allows you to create an expandable and collapsible information panel that can include text, images, and controls. Choose from four expand directions and position of the expand button..
        /// </summary>
        public static string Expander {
            get {
                return ResourceManager.GetString("Expander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expander.
        /// </summary>
        public static string ExpanderTitle {
            get {
                return ResourceManager.GetString("ExpanderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Color.
        /// </summary>
        public static string FavoriteColor {
            get {
                return ResourceManager.GetString("FavoriteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}.
        /// </summary>
        public static string FieldMustBeBetween {
            get {
                return ResourceManager.GetString("FieldMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form was validated!.
        /// </summary>
        public static string FormWasValidated {
            get {
                return ResourceManager.GetString("FormWasValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This library includes several WPF input controls for any data entry scenario. Format and parse numbers, dates, colors, and masked text. Select multiple items from a checklist or enter items like a tag editor. Edit a numeric range visually using a slider. Design a custom drop-down UI with ease. Select files from the user&apos;s machine..
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input tag&apos;s content:.
        /// </summary>
        public static string InputTagContent {
            get {
                return ResourceManager.GetString("InputTagContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input text:.
        /// </summary>
        public static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string InputTitle {
            get {
                return ResourceManager.GetString("InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use C1MaskedTextBox with different settings of Mask and TextMaskFormat..
        /// </summary>
        public static string MaskedDemoDes {
            get {
                return ResourceManager.GetString("MaskedDemoDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masked TextBox.
        /// </summary>
        public static string MaskedDemoTitle {
            get {
                return ResourceManager.GetString("MaskedDemoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        public static string MethodsTabHeader {
            get {
                return ResourceManager.GetString("MethodsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiSelect.
        /// </summary>
        public static string MultiSelect {
            get {
                return ResourceManager.GetString("MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use C1MultiSelect.
        /// </summary>
        public static string MultiSelectDes {
            get {
                return ResourceManager.GetString("MultiSelectDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherGender {
            get {
                return ResourceManager.GetString("OtherGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesTabHeader {
            get {
                return ResourceManager.GetString("PropertiesTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The C1RangeSlider control extends the basic slider control and provides two thumbs, making it possible for users to select a range. Users can drag each thumb individually or drag the center to modify both at the same time..
        /// </summary>
        public static string RangeSlider {
            get {
                return ResourceManager.GetString("RangeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Slider.
        /// </summary>
        public static string RangeSliderTitle {
            get {
                return ResourceManager.GetString("RangeSliderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveItems.
        /// </summary>
        public static string RemoveItemsEvent {
            get {
                return ResourceManager.GetString("RemoveItemsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAllMethod {
            get {
                return ResourceManager.GetString("SelectAllMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedItems.
        /// </summary>
        public static string SelectedItemsEvent {
            get {
                return ResourceManager.GetString("SelectedItemsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectionChangedEvent.
        /// </summary>
        public static string SelectionChangedEventExpenderHeader {
            get {
                return ResourceManager.GetString("SelectionChangedEventExpenderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        public static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a stops slider control allowing to drag the thumbs as well as adding new ones by clicking in the track and remove them with Del key..
        /// </summary>
        public static string StopsSliderDescription {
            get {
                return ResourceManager.GetString("StopsSliderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops Slider.
        /// </summary>
        public static string StopsSliderTitle {
            get {
                return ResourceManager.GetString("StopsSliderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use C1TagEditor..
        /// </summary>
        public static string TagEditorDemoDes {
            get {
                return ResourceManager.GetString("TagEditorDemoDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Editor.
        /// </summary>
        public static string TagEditorDemoTitle {
            get {
                return ResourceManager.GetString("TagEditorDemoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputExplorer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect All.
        /// </summary>
        public static string UnselectAllMethod {
            get {
                return ResourceManager.GetString("UnselectAllMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show how to use built-in validation through standard INotifyDataErrorInfo.
        /// </summary>
        public static string ValidationFormDescription {
            get {
                return ResourceManager.GetString("ValidationFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Form.
        /// </summary>
        public static string ValidationFormTitle {
            get {
                return ResourceManager.GetString("ValidationFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hours.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
    }
}
