<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>C1-ball.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="C1.DataCollection.EntityFrameworkCore" Version="10.0.20261.8" />
    <PackageReference Include="C1.WPF.Accordion">
      <Version>10.0.20261.125</Version>
    </PackageReference>
    <PackageReference Include="C1.WPF.Core">
      <Version>10.0.20261.125</Version>
    </PackageReference>
    <PackageReference Include="C1.WPF.DataFilter">
      <Version>10.0.20261.125</Version>
    </PackageReference>
    <PackageReference Include="C1.WPF.Grid">
      <Version>10.0.20261.125</Version>
    </PackageReference>
    <PackageReference Include="C1.WPF.Input">
      <Version>10.0.20261.125</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.8" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\AppResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\AppResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="SQLiteDataBase.sa3licx" />
  </ItemGroup>
</Project>