<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>preview</LangVersion>
    <ApplicationIcon>C1-ball.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove=".sa3licx" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="C1-ball.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include=".sa3licx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="C1.WPF.Grid">
      <Version>10.0.20261.47</Version>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="AppResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="AppResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>