//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexViewerExplorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexViewerExplorer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows how to create a custom toolbar with FlexViewer..
        /// </summary>
        internal static string CustomAppearanceDesc {
            get {
                return ResourceManager.GetString("CustomAppearanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Appearance.
        /// </summary>
        internal static string CustomAppearanceTitle {
            get {
                return ResourceManager.GetString("CustomAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows how to display FlexReport in FlexViewer..
        /// </summary>
        internal static string FlexReportViewerDesc {
            get {
                return ResourceManager.GetString("FlexReportViewerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexReport Viewer.
        /// </summary>
        internal static string FlexReportViewerTitle {
            get {
                return ResourceManager.GetString("FlexReportViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows how to display PDF document in FlexViewer..
        /// </summary>
        internal static string PdfViewerDesc {
            get {
                return ResourceManager.GetString("PdfViewerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf Viewer.
        /// </summary>
        internal static string PdfViewerTitle {
            get {
                return ResourceManager.GetString("PdfViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows how to load and display Ssrs reports in FlexViewer..
        /// </summary>
        internal static string SsrsViewerDesc {
            get {
                return ResourceManager.GetString("SsrsViewerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ssrs Viewer.
        /// </summary>
        internal static string SsrsViewerTitle {
            get {
                return ResourceManager.GetString("SsrsViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexViewerExplorer.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
