//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexGrid101.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexGrid101.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows frozen columns, rows and cell merging..
        /// </summary>
        public static string CellFreezingDescription {
            get {
                return ResourceManager.GetString("CellFreezingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Freezing &amp; Merging.
        /// </summary>
        public static string CellFreezingTitle {
            get {
                return ResourceManager.GetString("CellFreezingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cell(s) selected.
        /// </summary>
        public static string CellsSelectedText {
            get {
                return ResourceManager.GetString("CellsSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show how to select flexgrid rows through checkboxes..
        /// </summary>
        public static string CheckListDescription {
            get {
                return ResourceManager.GetString("CheckListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-List.
        /// </summary>
        public static string CheckListTitle {
            get {
                return ResourceManager.GetString("CheckListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports C1CollectionView to provide live sorting, filtering and grouping..
        /// </summary>
        public static string CollectionViewDescription {
            get {
                return ResourceManager.GetString("CollectionViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectionView.
        /// </summary>
        public static string CollectionViewName {
            get {
                return ResourceManager.GetString("CollectionViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to specify and format columns..
        /// </summary>
        public static string ColumnDefinitionDescription {
            get {
                return ResourceManager.GetString("ColumnDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Definitions.
        /// </summary>
        public static string ColumnDefinitionTitle {
            get {
                return ResourceManager.GetString("ColumnDefinitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a custom column manager to modify column layout..
        /// </summary>
        public static string ColumnLayoutDescription {
            get {
                return ResourceManager.GetString("ColumnLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Layout.
        /// </summary>
        public static string ColumnLayoutTitle {
            get {
                return ResourceManager.GetString("ColumnLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses a CellFactory to apply conditional formatting..
        /// </summary>
        public static string ConditionalFormattingDescription {
            get {
                return ResourceManager.GetString("ConditionalFormattingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Formatting.
        /// </summary>
        public static string ConditionalFormattingTitle {
            get {
                return ResourceManager.GetString("ConditionalFormattingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a grid with a custom style..
        /// </summary>
        public static string CustomAppearanceDescription {
            get {
                return ResourceManager.GetString("CustomAppearanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Appearance.
        /// </summary>
        public static string CustomAppearanceTitle {
            get {
                return ResourceManager.GetString("CustomAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizes a cell by displaying a library of about 10,000 songs grouped by artist and album..
        /// </summary>
        public static string CustomCellsDescription {
            get {
                return ResourceManager.GetString("CustomCellsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Cells.
        /// </summary>
        public static string CustomCellsTitle {
            get {
                return ResourceManager.GetString("CustomCellsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a grid with custom cell merging..
        /// </summary>
        public static string CustomMergingDescription {
            get {
                return ResourceManager.GetString("CustomMergingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Merging.
        /// </summary>
        public static string CustomMergingTitle {
            get {
                return ResourceManager.GetString("CustomMergingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show how to customize the sorting icon in header columns..
        /// </summary>
        public static string CustomSortIconDescription {
            get {
                return ResourceManager.GetString("CustomSortIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Sort Icon.
        /// </summary>
        public static string CustomSortIconTitle {
            get {
                return ResourceManager.GetString("CustomSortIconTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailsVisibiltyMode.
        /// </summary>
        public static string DetailsVisibiltyMode {
            get {
                return ResourceManager.GetString("DetailsVisibiltyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditColumnLayout {
            get {
                return ResourceManager.GetString("EditColumnLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to prompt the user with a confirmation dialog before committing changes to a cell..
        /// </summary>
        public static string EditConfirmationDescription {
            get {
                return ResourceManager.GetString("EditConfirmationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to commit the edit?.
        /// </summary>
        public static string EditConfirmationQuestion {
            get {
                return ResourceManager.GetString("EditConfirmationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Edit.
        /// </summary>
        public static string EditConfirmationQuestionTitle {
            get {
                return ResourceManager.GetString("EditConfirmationQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Confirmation.
        /// </summary>
        public static string EditConfirmationTitle {
            get {
                return ResourceManager.GetString("EditConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit cells by input form rather than inline..
        /// </summary>
        public static string EditingDescription {
            get {
                return ResourceManager.GetString("EditingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Form.
        /// </summary>
        public static string EditingTitle {
            get {
                return ResourceManager.GetString("EditingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Row.
        /// </summary>
        public static string EditRow {
            get {
                return ResourceManager.GetString("EditRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no videos to show..
        /// </summary>
        public static string EmptyListText {
            get {
                return ResourceManager.GetString("EmptyListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters the data by columns through a generated form..
        /// </summary>
        public static string FilterDescription {
            get {
                return ResourceManager.GetString("FilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to filter.
        /// </summary>
        public static string FilterPlaceholderText {
            get {
                return ResourceManager.GetString("FilterPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters the data by columns using a filter row..
        /// </summary>
        public static string FilterRowDescription {
            get {
                return ResourceManager.GetString("FilterRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterRow.
        /// </summary>
        public static string FilterRowTitle {
            get {
                return ResourceManager.GetString("FilterRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a financial application with real time data updates, flashing cells, and sparklines..
        /// </summary>
        public static string FinancialDescription {
            get {
                return ResourceManager.GetString("FinancialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial.
        /// </summary>
        public static string FinancialTitle {
            get {
                return ResourceManager.GetString("FinancialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters and highlights the data across all columns..
        /// </summary>
        public static string FullTextFilterDescription {
            get {
                return ResourceManager.GetString("FullTextFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Text Filter.
        /// </summary>
        public static string FullTextFilterTitle {
            get {
                return ResourceManager.GetString("FullTextFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display, edit and aggregate your data all at once with FlexGrid..
        /// </summary>
        public static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups and aggregates a collection of data..
        /// </summary>
        public static string GroupingDescription {
            get {
                return ResourceManager.GetString("GroupingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create groups by dragging column headers into the grouping areas..
        /// </summary>
        public static string GroupingPanelDescription {
            get {
                return ResourceManager.GetString("GroupingPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping Panel.
        /// </summary>
        public static string GroupingPanelTitle {
            get {
                return ResourceManager.GetString("GroupingPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string GroupingTitle {
            get {
                return ResourceManager.GetString("GroupingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string MatchCaseLabel {
            get {
                return ResourceManager.GetString("MatchCaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Whole Word.
        /// </summary>
        public static string MatchWholeWordLabel {
            get {
                return ResourceManager.GetString("MatchWholeWordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the effects of different settings of MouseOverMode.
        /// </summary>
        public static string MouseHoverDescription {
            get {
                return ResourceManager.GetString("MouseHoverDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Hover.
        /// </summary>
        public static string MouseHoverTitle {
            get {
                return ResourceManager.GetString("MouseHoverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows adding new rows..
        /// </summary>
        public static string NewRowDescription {
            get {
                return ResourceManager.GetString("NewRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add a new row.
        /// </summary>
        public static string NewRowPlaceholder {
            get {
                return ResourceManager.GetString("NewRowPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Row.
        /// </summary>
        public static string NewRowTitle {
            get {
                return ResourceManager.GetString("NewRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load items on demand as the user scrolls down the grid..
        /// </summary>
        public static string OnDemandDescription {
            get {
                return ResourceManager.GetString("OnDemandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Demand.
        /// </summary>
        public static string OnDemandTitle {
            get {
                return ResourceManager.GetString("OnDemandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand and collapse row details..
        /// </summary>
        public static string RowDetailsDescription {
            get {
                return ResourceManager.GetString("RowDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Details.
        /// </summary>
        public static string RowDetailsTitle {
            get {
                return ResourceManager.GetString("RowDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveColumnLayout {
            get {
                return ResourceManager.GetString("SaveColumnLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to search videos on YouTube.
        /// </summary>
        public static string SearchPlaceholderText {
            get {
                return ResourceManager.GetString("SearchPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the various cell selection modes..
        /// </summary>
        public static string SelectionModesDescription {
            get {
                return ResourceManager.GetString("SelectionModesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Modes.
        /// </summary>
        public static string SelectionModesTitle {
            get {
                return ResourceManager.GetString("SelectionModesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row first or double-tap the row directly..
        /// </summary>
        public static string SelectRowMessage {
            get {
                return ResourceManager.GetString("SelectRowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowMarquee.
        /// </summary>
        public static string ShowMarquee {
            get {
                return ResourceManager.GetString("ShowMarquee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a responsive column layout that uses star sizing..
        /// </summary>
        public static string StarSizingDescription {
            get {
                return ResourceManager.GetString("StarSizingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the device to see star-sizing in action..
        /// </summary>
        public static string StarSizingInstructions {
            get {
                return ResourceManager.GetString("StarSizingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Sizing.
        /// </summary>
        public static string StarSizingTitle {
            get {
                return ResourceManager.GetString("StarSizingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add empty rows and columns to create an unbound grid..
        /// </summary>
        public static string UnboundDescription {
            get {
                return ResourceManager.GetString("UnboundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbound.
        /// </summary>
        public static string UnboundTitle {
            get {
                return ResourceManager.GetString("UnboundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        public static string Weekend {
            get {
                return ResourceManager.GetString("Weekend", resourceCulture);
            }
        }
    }
}
