'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.ComponentModel

Partial Public Class Territory
	Implements INotifyPropertyChanged
    Public Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Protected Sub OnPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private _TerritoryID As String
    Public Property TerritoryID As String
        Get
            Return _TerritoryID
        End Get
        Set(ByVal value As String)
            _TerritoryID = value
            OnPropertyChanged("TerritoryID")
        End Set
    End Property

    Private _TerritoryDescription As String
    Public Property TerritoryDescription As String
        Get
            Return _TerritoryDescription
        End Get
        Set(ByVal value As String)
            _TerritoryDescription = value
            OnPropertyChanged("TerritoryDescription")
        End Set
    End Property

    Private _RegionID As Integer
    Public Property RegionID As Integer
        Get
            Return _RegionID
        End Get
        Set(ByVal value As Integer)
            _RegionID = value
            OnPropertyChanged("RegionID")
        End Set
    End Property


    Private _Region As Region
    Public Overridable Property Region As Region
        Get
            Return _Region
        End Get
        Set(ByVal value As Region)
            _Region = value
            OnPropertyChanged("Region")
        End Set
    End Property

    Private _Employees As ObservableCollection(Of Employee) = New ObservableCollection(Of Employee)
    Public Overridable Property Employees As ObservableCollection(Of Employee)
        Get
            Return _Employees
        End Get
        Set(ByVal value As ObservableCollection(Of Employee))
            _Employees = value
            OnPropertyChanged("Employees")
        End Set
    End Property

End Class
