//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    
    public partial class Shipper : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
    	protected void OnPropertyChanged(string propertyName)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    
        public Shipper()
        {
            this.Orders = new ObservableCollection<Order>();
        }
    
        int _ShipperID;
        public int ShipperID 
        {
            get { return _ShipperID; }
            set
            {
                _ShipperID = value;
                OnPropertyChanged("ShipperID");
            }
        }
        string _CompanyName;
        public string CompanyName 
        {
            get { return _CompanyName; }
            set
            {
                _CompanyName = value;
                OnPropertyChanged("CompanyName");
            }
        }
        string _Phone;
        public string Phone 
        {
            get { return _Phone; }
            set
            {
                _Phone = value;
                OnPropertyChanged("Phone");
            }
        }
    
        public virtual ObservableCollection<Order> Orders { get; set; }
    }
}
