//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparklineExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SparklineExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows that how to create the Sparkline control and change its appearance..
        /// </summary>
        public static string AppeareanceDescription {
            get {
                return ResourceManager.GetString("AppeareanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Appearance.
        /// </summary>
        public static string AppeareanceTitle {
            get {
                return ResourceManager.GetString("AppeareanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display DateAxis:.
        /// </summary>
        public static string DisplayDateAxisLabel {
            get {
                return ResourceManager.GetString("DisplayDateAxisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows how to use Sparklines in CellTemplates for FlexGrid columns..
        /// </summary>
        public static string GridDescription {
            get {
                return ResourceManager.GetString("GridDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexGrid Integration.
        /// </summary>
        public static string GridTitle {
            get {
                return ResourceManager.GetString("GridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Sales.
        /// </summary>
        public static string NetSalesColumnHeader {
            get {
                return ResourceManager.GetString("NetSalesColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Data.
        /// </summary>
        public static string NewDataButtonText {
            get {
                return ResourceManager.GetString("NewDataButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Trend.
        /// </summary>
        public static string ProfitTrendColumnHeader {
            get {
                return ResourceManager.GetString("ProfitTrendColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string RegionColumnHeader {
            get {
                return ResourceManager.GetString("RegionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows sparklines in a data bound ListBox..
        /// </summary>
        public static string RegionSalesDescription {
            get {
                return ResourceManager.GetString("RegionSalesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Sales.
        /// </summary>
        public static string RegionSalesTitle {
            get {
                return ResourceManager.GetString("RegionSalesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Trend.
        /// </summary>
        public static string SalesTrendColumnHeader {
            get {
                return ResourceManager.GetString("SalesTrendColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows that how to create different types of sparkline..
        /// </summary>
        public static string SparklineDemoDescription {
            get {
                return ResourceManager.GetString("SparklineDemoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparkline Demo.
        /// </summary>
        public static string SparklineDemoTitle {
            get {
                return ResourceManager.GetString("SparklineDemoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SparklineExplorer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        public static string TotalSalesColumnHeader {
            get {
                return ResourceManager.GetString("TotalSalesColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win/Loss.
        /// </summary>
        public static string WinLossColumnHeader {
            get {
                return ResourceManager.GetString("WinLossColumnHeader", resourceCulture);
            }
        }
    }
}
