'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.ComponentModel

Partial Public Class Employee
	Implements INotifyPropertyChanged
    Public Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Protected Sub OnPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private _EmployeeID As Integer
    Public Property EmployeeID As Integer
        Get
            Return _EmployeeID
        End Get
        Set(ByVal value As Integer)
            _EmployeeID = value
            OnPropertyChanged("EmployeeID")
        End Set
    End Property

    Private _LastName As String
    Public Property LastName As String
        Get
            Return _LastName
        End Get
        Set(ByVal value As String)
            _LastName = value
            OnPropertyChanged("LastName")
        End Set
    End Property

    Private _FirstName As String
    Public Property FirstName As String
        Get
            Return _FirstName
        End Get
        Set(ByVal value As String)
            _FirstName = value
            OnPropertyChanged("FirstName")
        End Set
    End Property

    Private _Title As String
    Public Property Title As String
        Get
            Return _Title
        End Get
        Set(ByVal value As String)
            _Title = value
            OnPropertyChanged("Title")
        End Set
    End Property

    Private _TitleOfCourtesy As String
    Public Property TitleOfCourtesy As String
        Get
            Return _TitleOfCourtesy
        End Get
        Set(ByVal value As String)
            _TitleOfCourtesy = value
            OnPropertyChanged("TitleOfCourtesy")
        End Set
    End Property

    Private _BirthDate As Nullable(Of Date)
    Public Property BirthDate As Nullable(Of Date)
        Get
            Return _BirthDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            _BirthDate = value
            OnPropertyChanged("BirthDate")
        End Set
    End Property

    Private _HireDate As Nullable(Of Date)
    Public Property HireDate As Nullable(Of Date)
        Get
            Return _HireDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            _HireDate = value
            OnPropertyChanged("HireDate")
        End Set
    End Property

    Private _Address As String
    Public Property Address As String
        Get
            Return _Address
        End Get
        Set(ByVal value As String)
            _Address = value
            OnPropertyChanged("Address")
        End Set
    End Property

    Private _City As String
    Public Property City As String
        Get
            Return _City
        End Get
        Set(ByVal value As String)
            _City = value
            OnPropertyChanged("City")
        End Set
    End Property

    Private _Region As String
    Public Property Region As String
        Get
            Return _Region
        End Get
        Set(ByVal value As String)
            _Region = value
            OnPropertyChanged("Region")
        End Set
    End Property

    Private _PostalCode As String
    Public Property PostalCode As String
        Get
            Return _PostalCode
        End Get
        Set(ByVal value As String)
            _PostalCode = value
            OnPropertyChanged("PostalCode")
        End Set
    End Property

    Private _Country As String
    Public Property Country As String
        Get
            Return _Country
        End Get
        Set(ByVal value As String)
            _Country = value
            OnPropertyChanged("Country")
        End Set
    End Property

    Private _HomePhone As String
    Public Property HomePhone As String
        Get
            Return _HomePhone
        End Get
        Set(ByVal value As String)
            _HomePhone = value
            OnPropertyChanged("HomePhone")
        End Set
    End Property

    Private _Extension As String
    Public Property Extension As String
        Get
            Return _Extension
        End Get
        Set(ByVal value As String)
            _Extension = value
            OnPropertyChanged("Extension")
        End Set
    End Property

    Private _Photo As Byte()
    Public Property Photo As Byte()
        Get
            Return _Photo
        End Get
        Set(ByVal value As Byte())
            _Photo = value
            OnPropertyChanged("Photo")
        End Set
    End Property

    Private _Notes As String
    Public Property Notes As String
        Get
            Return _Notes
        End Get
        Set(ByVal value As String)
            _Notes = value
            OnPropertyChanged("Notes")
        End Set
    End Property

    Private _ReportsTo As Nullable(Of Integer)
    Public Property ReportsTo As Nullable(Of Integer)
        Get
            Return _ReportsTo
        End Get
        Set(ByVal value As Nullable(Of Integer))
            _ReportsTo = value
            OnPropertyChanged("ReportsTo")
        End Set
    End Property

    Private _PhotoPath As String
    Public Property PhotoPath As String
        Get
            Return _PhotoPath
        End Get
        Set(ByVal value As String)
            _PhotoPath = value
            OnPropertyChanged("PhotoPath")
        End Set
    End Property


    Private _Employees1 As ObservableCollection(Of Employee) = New ObservableCollection(Of Employee)
    Public Overridable Property Employees1 As ObservableCollection(Of Employee)
        Get
            Return _Employees1
        End Get
        Set(ByVal value As ObservableCollection(Of Employee))
            _Employees1 = value
            OnPropertyChanged("Employees1")
        End Set
    End Property

    Private _Employee1 As Employee
    Public Overridable Property Employee1 As Employee
        Get
            Return _Employee1
        End Get
        Set(ByVal value As Employee)
            _Employee1 = value
            OnPropertyChanged("Employee1")
        End Set
    End Property

    Private _Orders As ObservableCollection(Of Order) = New ObservableCollection(Of Order)
    Public Overridable Property Orders As ObservableCollection(Of Order)
        Get
            Return _Orders
        End Get
        Set(ByVal value As ObservableCollection(Of Order))
            _Orders = value
            OnPropertyChanged("Orders")
        End Set
    End Property

    Private _Territories As ObservableCollection(Of Territory) = New ObservableCollection(Of Territory)
    Public Overridable Property Territories As ObservableCollection(Of Territory)
        Get
            Return _Territories
        End Get
        Set(ByVal value As ObservableCollection(Of Territory))
            _Territories = value
            OnPropertyChanged("Territories")
        End Set
    End Property

End Class
