<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ApplicationIcon>C1-ball.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <None Remove=".sa3licx" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include=".sa3licx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="C1.WPF.Calendar">
      <Version>10.0.20261.125</Version>
    </PackageReference>
    <PackageReference Include="C1.WPF.Core">
      <Version>10.0.20261.125</Version>
    </PackageReference>
    <PackageReference Include="C1.WPF.Docking">
      <Version>10.0.20261.125</Version>
    </PackageReference>
    <PackageReference Include="C1.WPF.Grid">
      <Version>10.0.20261.125</Version>
    </PackageReference>
    <PackageReference Include="C1.WPF.Schedule">
      <Version>10.0.20261.125</Version>
    </PackageReference>
    <PackageReference Include="C1.WPF.TabControl">
      <Version>10.0.20261.125</Version>
    </PackageReference>
  </ItemGroup>
</Project>