//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListViewExplorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListViewExplorer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to style the items of the list..
        /// </summary>
        public static string CustomAppearanceDescription {
            get {
                return ResourceManager.GetString("CustomAppearanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Appearance.
        /// </summary>
        public static string CustomAppearanceTitle {
            get {
                return ResourceManager.GetString("CustomAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use custom DataTemplate with C1ListView..
        /// </summary>
        public static string CustomTemplateDescription {
            get {
                return ResourceManager.GetString("CustomTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Template.
        /// </summary>
        public static string CustomTemplateTitle {
            get {
                return ResourceManager.GetString("CustomTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to filter a list or item just by tying in a text box..
        /// </summary>
        public static string FilterDescription {
            get {
                return ResourceManager.GetString("FilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        public static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to load photos from Flickr, shows preview when photo is not fully loaded yet.
        /// </summary>
        public static string FlickrDescription {
            get {
                return ResourceManager.GetString("FlickrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving data from Flickr....
        /// </summary>
        public static string FlickrRetrievingData {
            get {
                return ResourceManager.GetString("FlickrRetrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flickr.
        /// </summary>
        public static string FlickrTitle {
            get {
                return ResourceManager.GetString("FlickrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Born.
        /// </summary>
        public static string GroupByBorn {
            get {
                return ResourceManager.GetString("GroupByBorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Resident.
        /// </summary>
        public static string GroupByResident {
            get {
                return ResourceManager.GetString("GroupByResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a grouped list of items..
        /// </summary>
        public static string GroupDescription {
            get {
                return ResourceManager.GetString("GroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string GroupTitle {
            get {
                return ResourceManager.GetString("GroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1ListView Explorer.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With on-demand loading, C1ListView loads items as the user scrolls. Since the list does not know the total number of rows, the scroll bar size and position changes as more data is loaded into view. This virtualization technique is supported by the help of C1DataCollection..
        /// </summary>
        public static string OnDemandDescription {
            get {
                return ResourceManager.GetString("OnDemandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Demand.
        /// </summary>
        public static string OnDemandTitle {
            get {
                return ResourceManager.GetString("OnDemandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation:.
        /// </summary>
        public static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a ListView with paging using C1ListView, C1DataPager and C1DataCollection. Like the virtual mode and on-demand loading, paging is supported in C1ListView by the help of C1DataCollection..
        /// </summary>
        public static string PagingDescription {
            get {
                return ResourceManager.GetString("PagingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging.
        /// </summary>
        public static string PagingTitle {
            get {
                return ResourceManager.GetString("PagingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here to filter.
        /// </summary>
        public static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Grouping.
        /// </summary>
        public static string RemoveGrouping {
            get {
                return ResourceManager.GetString("RemoveGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Mode:.
        /// </summary>
        public static string SelectionMode {
            get {
                return ResourceManager.GetString("SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Check Box.
        /// </summary>
        public static string ShowCheckBox {
            get {
                return ResourceManager.GetString("ShowCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Select All.
        /// </summary>
        public static string ShowSelectAll {
            get {
                return ResourceManager.GetString("ShowSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort ascendingly.
        /// </summary>
        public static string SortAscendingly {
            get {
                return ResourceManager.GetString("SortAscendingly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort descendingly.
        /// </summary>
        public static string SortDescendingly {
            get {
                return ResourceManager.GetString("SortDescendingly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can easily sort the C1ListView asynchronously in either direction through the C1DataCollection..
        /// </summary>
        public static string SortDescription {
            get {
                return ResourceManager.GetString("SortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string SortTitle {
            get {
                return ResourceManager.GetString("SortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how ItemContainerStyleSelector works.
        /// </summary>
        public static string StyleSelectorDesc {
            get {
                return ResourceManager.GetString("StyleSelectorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Selector.
        /// </summary>
        public static string StyleSelectorTitle {
            get {
                return ResourceManager.GetString("StyleSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to customize style of items using ItemContainerStyle.
        /// </summary>
        public static string StylingDesc {
            get {
                return ResourceManager.GetString("StylingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Container Style.
        /// </summary>
        public static string StylingTitle {
            get {
                return ResourceManager.GetString("StylingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to customize template of items using TemplateSelector.
        /// </summary>
        public static string TemplateSelectorDesc {
            get {
                return ResourceManager.GetString("TemplateSelectorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Selector.
        /// </summary>
        public static string TemplateSelectorTitle {
            get {
                return ResourceManager.GetString("TemplateSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile List View.
        /// </summary>
        public static string TileListView {
            get {
                return ResourceManager.GetString("TileListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how Tile List View works..
        /// </summary>
        public static string TileListViewTag {
            get {
                return ResourceManager.GetString("TileListViewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbound.
        /// </summary>
        public static string Unbound {
            get {
                return ResourceManager.GetString("Unbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to add ListViewItem on xaml directly..
        /// </summary>
        public static string UnbounDesc {
            get {
                return ResourceManager.GetString("UnbounDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1ListView supports data virtualization for loading large data sets in chunks or pages as the user scrolls. The list knows the total number of rows but only loads and displays those that are visible to the user. This virtualization technique is supported by the help of C1DataCollection..
        /// </summary>
        public static string VirtualModeDescription {
            get {
                return ResourceManager.GetString("VirtualModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Mode.
        /// </summary>
        public static string VirtualModeTitle {
            get {
                return ResourceManager.GetString("VirtualModeTitle", resourceCulture);
            }
        }
    }
}
