//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreExplorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreExplorer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows how you can drag and drop between two UI controls using C1DragDropManager..
        /// </summary>
        internal static string DemoListTag {
            get {
                return ResourceManager.GetString("DemoListTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use C1ProgressBar, change its mode and customize appearance.
        /// </summary>
        internal static string DemoProgressBarDescription {
            get {
                return ResourceManager.GetString("DemoProgressBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Bar.
        /// </summary>
        internal static string DemoProgressBarTitle {
            get {
                return ResourceManager.GetString("DemoProgressBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Drop ListBox.
        /// </summary>
        internal static string DragDropListBoxDescription {
            get {
                return ResourceManager.GetString("DragDropListBoxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Drop ListBox.
        /// </summary>
        internal static string DragDropListBoxTitle {
            get {
                return ResourceManager.GetString("DragDropListBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Drop Manager.
        /// </summary>
        internal static string DragDropManagerDescription {
            get {
                return ResourceManager.GetString("DragDropManagerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1DragDropManager has an extensive set of methods and events that allow you to control the entire drag-and-drop process. Just register some elements as drag sources and some as drop targets, and then handle the DragDrop event to move or copy the elements to their new location. You can also customize the appearance of the drag markers for both the drag source and drop target. This makes the entire operation more user-friendly and visually appealing..
        /// </summary>
        internal static string DragDropManagerTag {
            get {
                return ResourceManager.GetString("DragDropManagerTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Drop Manager.
        /// </summary>
        internal static string DragDropManagerTitle {
            get {
                return ResourceManager.GetString("DragDropManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Handling.
        /// </summary>
        internal static string InputHandlingDescription {
            get {
                return ResourceManager.GetString("InputHandlingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Handling.
        /// </summary>
        internal static string InputHandlingTitle {
            get {
                return ResourceManager.GetString("InputHandlingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Again.
        /// </summary>
        internal static string PlayAgain {
            get {
                return ResourceManager.GetString("PlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Again.
        /// </summary>
        internal static string RunAgain {
            get {
                return ResourceManager.GetString("RunAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The C1TapHelper, C1ZoomHelper, and C1DragHelper classes help listening to drag and zoom gestures supporting inertiaand  either using the mouse or fingers..
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoreExplorer.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
