'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.ComponentModel

Partial Public Class CustomerDemographic
	Implements INotifyPropertyChanged
    Public Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Protected Sub OnPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private _CustomerTypeID As String
    Public Property CustomerTypeID As String
        Get
            Return _CustomerTypeID
        End Get
        Set(ByVal value As String)
            _CustomerTypeID = value
            OnPropertyChanged("CustomerTypeID")
        End Set
    End Property

    Private _CustomerDesc As String
    Public Property CustomerDesc As String
        Get
            Return _CustomerDesc
        End Get
        Set(ByVal value As String)
            _CustomerDesc = value
            OnPropertyChanged("CustomerDesc")
        End Set
    End Property


    Private _Customers As ObservableCollection(Of Customer) = New ObservableCollection(Of Customer)
    Public Overridable Property Customers As ObservableCollection(Of Customer)
        Get
            Return _Customers
        End Get
        Set(ByVal value As ObservableCollection(Of Customer))
            _Customers = value
            OnPropertyChanged("Customers")
        End Set
    End Property

End Class
